### ISSUE TITLE
Accountant Error

### ISSUE THREAD

**Issue by CharlieDelune** [Ottermandias/Accountant#11]
Had the accountant plugin installed when it was updated for Endwalker. It worked for the better part of two days, and then at one point after changing zones, the Accountant Error window popped up

> The plugin Accountant ran into an error. Contact the plugin developer for support. Please try restarting your game.

Restarting the game (several times) did nothing, so I uninstalled the plugin, manually deleted all leftover folders relevant to it, and then reinstalled it. This time, the error popped up instantly.

Not sure what you need from me to narrow down what the issue is, but happy to help.

**Comment by CharlieDelune** [comment]
The dalamud discord plugin, Franzbot, pulled this out of my dalamud.log:

> Dalamud.log parse results for LASTEXCEPTION
> Franzbot has parsed your logfile. Here's some information about the last issue found in your log file.
> Info
> System.IndexOutOfRangeException: Index was outside the bounds of the array.   at Accountant.Gui.Timer.TimerWindow.RetainerCache.GenerateRetainer(RetainerInfo retainer, ObjectCounter& counter) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.RetainerCache.cs:line 27   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)   at Accountant.Gui.Timer.TimerWindow.RetainerCache.GeneratePlayer(String player, IEnumerable`1 retainers, ObjectCounter& globalCount) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.RetainerCache.cs:line 50
> Info
>    at Accountant.Gui.Timer.TimerWindow.RetainerCache.UpdateInternal() in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.RetainerCache.cs:line 70   at Accountant.Gui.Timer.TimerWindow.BaseCache.Update(DateTime now) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.BaseCache.cs:line 63   at Accountant.Gui.Timer.TimerWindow.BaseCache.Draw(DateTime now) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.BaseCache.cs:line 77   at Accountant.Gui.Timer.TimerWindow.Draw() in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\TimerWindow.cs:line 126   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 287
> Info continued
> ``````
> Context
> ["Accountant"] UiBuilder OnBuildUi caught exception
> System.IndexOutOfRangeException: Index was outside the bounds of the array.   at Accountant.Gui.Timer.TimerWindow.RetainerCache.GenerateRetainer(RetainerInfo retainer, ObjectCounter& counter) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.RetainerCache.cs:line 27   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)   at Accountant.Gui.Timer.TimerWindow.RetainerCache.GeneratePlayer(String player, IEnumerable`1 retainers, ObjectCounter& globalCount) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.RetainerCache.cs:line 50
> Context
>    at Accountant.Gui.Timer.TimerWindow.RetainerCache.UpdateInternal() in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.RetainerCache.cs:line 70   at Accountant.Gui.Timer.TimerWindow.BaseCache.Update(DateTime now) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.BaseCache.cs:line 63   at Accountant.Gui.Timer.TimerWindow.BaseCache.Draw(DateTime now) in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\Cache\TimerWindow.BaseCache.cs:line 77   at Accountant.Gui.Timer.TimerWindow.Draw() in H:\Projects\FFPlugins\Accountant\Accountant\Gui\Timer\TimerWindow.cs:line 126   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 287
> Context continued
> ``````
> Timestamp
> 2021-12-10T08:56:09.581599-05:00
> Friday, December 10, 2021 8:56 AM

**Comment by CharlieDelune** [comment]
Fixed in 8a4dfbb96f16ec783f06ff63d897b3bc34bbb995
