### ISSUE TITLE
Jumbo cacpot crash plugins

### ISSUE THREAD

**Issue by DianeAda** [Ottermandias/Accountant#6]
Hey ! I did the jumbo cacpot and plugins crashed. Impossible to make it work anymore even after restarting game or disable/enable plugins :( 

![image](https://user-images.githubusercontent.com/95047231/143763103-a3fc6723-5437-4c66-9a49-51e8fd6a429c.png)

**Comment by Korddie** [comment]
same for me , french client .
crash on first buy jumbo cactpot ticket, and now, each load crash plugin .
jumbo cacpot is call 'Méga Cactpot" in french . ticket sell by "Courtière"
i hope you can fix this , i love your calendar ^^

**Comment by Geoodees** [comment]
My whole client crashes with this exception,
`2021-11-28 12:27:38.387 +01:00 [FTL] Unhandled exception on AppDomain
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, DateTimeKind kind)
   at Accountant.Classes.JumboCactpot.NextReset(DateTime time, UInt16 worldId) in H:\Projects\FFPlugins\Accountant\Accountant\Classes\SaucerInfo.cs:line 86
   at Accountant.Timers.TaskTimers.AddOrUpdateJumbo(PlayerInfo player, UInt16 ticket) in H:\Projects\FFPlugins\Accountant\Accountant\Timers\TaskTimers.cs:line 189
   at Accountant.Manager.TimerManager.JumboCactpotManager.TicketBought(IntPtr _, Boolean which, SeString button, SeString description) in H:\Projects\FFPlugins\Accountant\Accountant\Manager\TimerManager.JumboCactpotManager.cs:line 112
   at AddonWatcher.Internal.AddonWatcherBase.SelectYesNoEventDetour(IntPtr atkUnit, EventType eventType, Int32 which, IntPtr source, IntPtr data) in H:\Projects\FFPlugins\Accountant\AddonWatcher\Internal\AddonWatcherBaseDetours.cs:line 56
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 264`

**Comment by Ottermandias** [comment]
Should be fixed.

**Comment by jackolas-lock** [comment]
I was having this problem, and it is fixed for me. Thanks!!
